keybinds:
  preset: wasd

strategems:

  - name: Jump Pack
    category: Backpacks
    code: DUUDU

  - name: Supply Pack
    category: Backpacks
    code: DLDUUD

  - name: \"Guard Dog" Rover
    category: Backpacks
    code: DULURR

  - name: Ballistic Shield Backpack
    category: Backpacks
    code: DLDDUL

  - name: Shield Generator Pack
    category: Backpacks
    code: DULRLR

  - name: \"Guard Dog"
    category: Backpacks
    code: DULURD

  - name: Machine Gun
    category: Support Weapons
    code: DLDUR

  - name: Anti-Materiel Rifle
    category: Support Weapons
    code: DLRUD

  - name: Stalwart
    category: Support Weapons
    code: DLDUUL

  - name: Expendable Anti-tank
    category: Support Weapons
    code: DDLUR

  - name: Recoilless Rifle
    category: Support Weapons
    code: DLRRL

  - name: Flamethrower
    category: Support Weapons
    code: DLUDU

  - name: Autocannon
    category: Support Weapons
    code: DLDUUR

  - name: Railgun
    category: Support Weapons
    code: DRDULR

  - name: SPEAR Launcher
    category: Support Weapons
    code: DDUDD

  - name: Grenade Launcher
    category: Support Weapons
    code: DLULD

  - name: Laser Cannon
    category: Support Weapons
    code: DLDUL

  - name: Arc Thrower
    category: Support Weapons
    code: DRDULL

  - name: Reinforce
    category: Support Weapons
    code: UDRLU

  - name: SOS Beacon
    category: Mission Strategems
    code: UDRU

  - name: Resupply
    category: Mission Strategems
    code: DDUR

  - name: Hellbomb
    category: Mission Strategems
    code: DULDURDU

  - name: SSSD Delivery
    category: Mission Strategems
    code: DDDUU

  - name: Seismic Probe
    category: Mission Strategems
    code: UULRDD

  - name: Upload Data
    category: Mission Strategems
    code: DDUUU

  - name: Eagle Rearm
    category: Mission Strategems
    code: UULUR

  - name: Illumination Flare
    category: Mission Strategems
    code: RRLL

  - name: SEAF Artillery
    category: Mission Strategems
    code: RUUD

  - name: Super Earth Flag
    category: Mission Strategems
    code: DUDU

  - name: HMG Emplacement
    category: Defensive
    code: DULRRL

  - name: Shield Generator Relay
    category: Defensive
    code: DDLRLR

  - name: Tesla Tower
    category: Defensive
    code: DURULR

  - name: Anti-Personnel Minefield
    category: Defensive
    code: DLUR

  - name: Incendiary Mines
    category: Defensive
    code: DLLD

  - name: Machine Gun Sentry
    category: Defensive
    code: DURRU

  - name: Gatling Sentry
    category: Defensive
    code: DURL

  - name: Mortar Sentry
    category: Defensive
    code: DURRD

  - name: Autocannon Sentry
    category: Defensive
    code: DURULU

  - name: Rocket Sentry
    category: Defensive
    code: DURRL

  - name: EMS Mortar Sentry
    category: Defensive
    code: DURDR

  - name: Orbital Gatling Barrage
    category: Orbital
    code: RDLUU

  - name: Orbital Airburst Strike
    category: Orbital
    code: RRR

  - name: Orbital 120MM HE Barrage
    category: Orbital
    code: RRDLRD

  - name: Orbital 380MM HE Barrage
    category: Orbital
    code: RDUULDD

  - name: Orbital Walking Barrage
    category: Orbital
    code: RDRDRD

  - name: Orbital Laser
    category: Orbital
    code: RDURD

  - name: Orbital Railcannon Strike
    category: Orbital
    code: RUDDR

  - name: Orbital Precision Strike
    category: Orbital
    code: RRU

  - name: Orbital Gas Strike
    category: Orbital
    code: RRDR

  - name: Orbital EMS Strike
    category: Orbital
    code: RRLD

  - name: Orbital Smoke Strike
    category: Orbital
    code: RRDU

  - name: Eagle Strafing Run
    category: Eagle
    code: URR

  - name: Eagle Airstrike
    category: Eagle
    code: URDR

  - name: Eagle Cluster Bomb
    category: Eagle
    code: URDDR

  - name: Eagle Napalm Airstrike
    category: Eagle
    code: URDU

  - name: Eagle Smoke Strike
    category: Eagle
    code: URUD

  - name: Eagle 110MM Rocket Pods
    category: Eagle
    code: URUL

  - name: Eagle 500kg Bomb
    category: Eagle
    code: URDDD

  - name: Patriot Exosuit
    category: Vehicles
    code: LDRULDD
